### ISSUE TITLE
(Issue/Suggestion) Early Game Combat Too Rough

### ISSUE THREAD

**Issue by rybplayer** [wideblaze/DigSite#10]
Hello,

Have to say I am really enjoying your pack. Just wanted to pull out an issue/suggestion regarding early game combat, specifically when players attempt to enter the digsite. 

Somehow in my world skeletons continually spawn in the cave before the entrance to the desert temple. By continually I mean way way too frequently.

Since in the early game I have only enough hearts and armor to withstand 2 arrow shots, that place becomes a nightmare. I placed a bed nearby and "spawncamped" trying to defeat the skeletons, but I kept dying simply because every time one died, another one appeared.

I cannot seem to be able to locate a spawner anywhere nearby, even if I change gamemodes, and light does not affect the spawning.

My workaround was to simply dig my own tunnel to the tomb.

Is this spawning intentional?

**Comment by Turmfalke2** [comment]
I also had to go through several corpse runs at the beginning of the game due to skeletons. I however found a simple shield helps immensely, as in it allows me to kill enough monsters to slowly gain hearts before I eventually fuck up and die. Maybe making a shield could be recommened in the quest book?

**Comment by wideblaze** [comment]
Rybplayer - It’s purposely difficult (but not impossible) — and you found one of several solutions to the problem. Most problems have 3 or more solutions.

I will include shields 🛡loot nearby and have the fisherman recommend in next release — great idea Termfalke2

**Comment by wideblaze** [comment]
release 1.0.05 includes shield quest, fisherman now says bring shield, shields (multi-color selection) now found in Lucville
