### ISSUE TITLE
Matter Overdrive Androids Shift In and Out of Existence

### ISSUE THREAD

**Issue by rybplayer** [wideblaze/DigSite#12]
Matter Overdrive Androids in the surface part of the flame appear to constantly shift in and out of existence:

Attempting to snipe androids with a bow and arrow(s) becomes dificult as androids somehow can appear and disappear from sight depending on where you are. Getting close to them can sometimes cause them to dissapear, and getting away sometimes cause them to reappear, and vice versa as well. However, when in exteremely close range to the player, namely when they start shooting you, the androids always become visible.

Is this merely a glitch on my part or is it an issue with the androids themselves?

**Comment by wideblaze** [comment]
I believe this is working as intended by the matter overdrive mod -- I will have to investigate.
