### ISSUE TITLE
(Suggestion) Matter Overdrive Androids Guarding the Flame Pose Too Little of a Threat

### ISSUE THREAD

**Issue by rybplayer** [wideblaze/DigSite#13]
I think I will regret posting this.

The androids guarding the surface entrance to the flame does not prevent players from just speedrunning to the gun.

It is in fact possible to simply run in, break the glass, and enter the portal to the flame. The leather armor given at the start (or the chainmail helmet and chainmail leggings) as well as an additional heart is enough to completely run through their defences.

The reason I believe this occurs is due to minecraft's entity invunerability state. In theory they should have enough **combined** power to one-shot you in your attempt. However as their guns merely shoot out high speed laser **projectiles,** the lasers all arrive at very slightly different times, and since the player becomes invunerable for a short time after being hit by the first laser, the player survives the barrage. That gives the player enough time to break the glass and run in. At least that's how I think my break and run was possible.

My suggestion is to increase the damage that the androids do just slightly that they can one-shot a low-armored player, but their shots still are nothing complared to diamond armor.

(Note: The androids inside the flame itself can be defeated by a mixture of walls, fire from matchboxes, as well as hits from the sword. Tunneling is also a very good strategy. The /sethome command also allows players to spawncamp their way through)

**Comment by wideblaze** [comment]
interesting -- thanks for the strategy details

I will have to check to make sure I didn't break the surface gate during last map edit -- should not be able to use surface gate until flame quest active. I understand tunneling is still an option.

> My suggestion is to increase the damage that the androids

I have an open request with C4 to have champions mod enhanced to be able to create custom champions at specific coords -- this is one of the planned locations for this enhancement -- no date given for enhancement by C4

**Comment by wideblaze** [comment]
C4 2:07AM
“No worries, it's alright. Sorry it's taking a while, it's definitely on the to-do list and will be in the next Champions update whenever that may be.”

**Comment by wideblaze** [comment]
Summonat coords custom champions for champions mod got released today. Will start playing with tomorrow— hopefully some custom champions in next modpack release

**Comment by wideblaze** [comment]
1.0.08 contains custom champion guards
