### ISSUE TITLE
Invisible ladders

### ISSUE THREAD

**Issue by iisworm** [wideblaze/DigSite#16]
The Rusty Ladders from MalisisDoors are invisible. I'm not sure if it's due to Optifine (or one of it's options) but I will test all of those options and see if this is resolved.

https://aeswere.ca/images/gktfev.png - Proof

**Comment by wideblaze** [comment]
Adding Optifine is known to introduce a number of render glitches and is considered a modification of the pack. 

work around: play despite glitches or remove optifine

From the DigSite FAQ https://github.com/wideblaze/DigSite/wiki/Frequently-Asked-Questions

> Q: Can I use Optifine, shaders, resource packs?
> 
> a: Using these might uncover hidden blocks or cause render glitches esp. when using portal gun. However, if you are ok with these minor issues then yes.

**Comment by iisworm** [comment]
Alright, thanks for the answer.
