### ISSUE TITLE
Main Questline gone after updating to DigSite 1.0.16

### ISSUE THREAD

**Issue by SurvivalHorst** [wideblaze/DigSite#18]
I've been progressing to The Flame Station yesterday and finished with having to repair the Flame Station's Factory.
Today I updated the server + client to DigSite 1.0.16. After logging in, my main questline is gone though. My friend (same server) still does have his main quest.

All I have for now is a sidequest (Looking for Tillmann) which I wasn't able to finish yesterday as Tillmann wouldn't talk to us unfortunately. And the Team mission (Discover the truth).

 Is there a way for me to fix this? Picking up the main quest line again that is.

Cheers and thanks for all your fantastic work!!

**Comment by SurvivalHorst** [comment]
Having continued to play today (still on it) I realized that there is going to be a endgame quest category. So this doesn't seem to be broken - just a bit irritating?

Cheers,
SurvivalHorst

**Comment by wideblaze** [comment]
Sorry for the late reply but it’s not the update. The quest line picks back up when you follow the note the prisoner hands you in the flame.

**Comment by SurvivalHorst** [comment]
Perfect. Sorry for the trouble - I guess it was simply confusing for us to play late, update the server the next day and then realizing the main quest line has come to an end without noticing before the update (for us it simply looked as if the quest line disappeared ;) ).
We're back on track already after having followed the note ^^.

Again, thanks for this amazing pack!

**Comment by wideblaze** [comment]
No worries, I could see how that could happen
