### ISSUE TITLE
Immediate crash after start

### ISSUE THREAD

**Issue by tracyd7177** [wideblaze/DigSite#21]
I start modpack from Twitch after recent update and after I hit the start button, the game crashes immediately. doesn't even try to load the game. It was fine before the recent update.

**Comment by wideblaze** [comment]
please paste crash report
thanks!

**Comment by tracyd7177** [comment]
I deleted it and reinstalled it and it loaded. :)

**Comment by wideblaze** [comment]
ok great, thanks for the info!
