### ISSUE TITLE
Launching the game failed! Failed to download file, the file contents differ from what was expected. Name: jna-4.4.0.jar

### ISSUE THREAD

**Issue by bradystrang15** [wideblaze/DigSite#26]
i downloaded digsite though the twitch app and when i press play it opens my minecraft but when i try to launch the modpack i get an error saying Launching the game failed
![crash](https://user-images.githubusercontent.com/20919813/71769057-c169f280-2ef6-11ea-809f-6b79d4e84baa.png)

**Comment by bradystrang15** [comment]
oh, i should also add ive completely reinstalled minecraft and the modpack multiple times

**Comment by thugitriot** [comment]
copy and past the url it gives you at the top to the jna-4.4.0 .jar file, then copy and past the path it gives you to find the folder where the .jar file normally is and replace the one in there with the one you downloaded, had the same problem and what ive done fixed mine

**Comment by thugitriot** [comment]
paste the url into a browser to get the file*

**Comment by wideblaze** [comment]
https://bugs.mojang.com/plugins/servlet/mobile#issue/MCL-12570

**Comment by wideblaze** [comment]
If you are seeing an error that says: "Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar"

This is a known Minecraft bug. Follow these instructions to fix: https://youtu.be/xAnj0aVDT1A

**Comment by wideblaze** [comment]
No new reports of this issue since Jan. I assume Twitch has "fixed the glitch" the above solution resolves this problem if it shows up again.
