### ISSUE TITLE
Unsecured Creative Air Compressors

### ISSUE THREAD

**Issue by LettingYouKnowICantCode** [wideblaze/DigSite#29]
So basically in the structure named "The Squid" I found it quite easily to obtain the creative compressors you've used, it might not be a huge problem if you're a common player and aren't trying to locate the location of these. I'd just recommend making the bedrock around them thicker and farther from player sight. :)

**Comment by wideblaze** [comment]
Thanks! I did some major remodeling there Recently and didn’t attempt to dig out as a player after.

**Comment by wideblaze** [comment]
secured in 1.0.27
