### ISSUE TITLE
Unlucky name of Failed Chickens for German users.

### ISSUE THREAD

**Issue by RustyXXL** [wideblaze/DigSite#31]
Just for your information. the Short "ficken" for failed Chicken means "to fuck" in german ;)

**Comment by wideblaze** [comment]
It was completely unintentional but most who see it get a good laugh

**Comment by RustyXXL** [comment]
Yeah, wasn't really a complaint or something, my son in puberty got especially a good laugh out of it. Just thought I'd mention it, not all parents are that relaxed. ;)
