### ISSUE TITLE
Single-player world - missing special mobs with stars.

### ISSUE THREAD

**Issue by Karl-Markkus** [wideblaze/DigSite#35]
Hello.

I am currently playing DigSite modpack installed directly from Twitch app.

The problem is, I am not meeting ANY of the so-called "mini-bosses" like the mobs with stars on 
them. (One in the LucVille secret underground storage and maybe one in the desert digsite main chamber)

Do I have to make my own server or order a server hosting to get them to spawn or is there another way?

Hopefully this is not a stupid inconvenience.

Regards,

Karl-Markkus

**Comment by Karl-Markkus** [comment]
I've encountered another problem: upon reaching the village near the squid station

![2020-01-22_13 10 16](https://user-images.githubusercontent.com/34920334/73005403-30a57900-3e09-11ea-874b-ada5263359b6.png)

It seems to have mostly burned down... Why?

**Comment by wideblaze** [comment]
The burned down village is part of the story

**Comment by wideblaze** [comment]
Tiered mobs are a % chance. You can increase difficulty to hard if you want a more deadly experience

**Comment by Karl-Markkus** [comment]
Okay, sorry if this was a small and irrelevant inconvenience, I just watched some other youtubers play this pack and they got the same tiered mobs in the same places... I thought it would'ove happened to me too.

**Comment by Karl-Markkus** [comment]
Thanks for clarifying though, now I can play it in peace ;p
