### ISSUE TITLE
flame not working 100% correct

### ISSUE THREAD

**Issue by minecraftguy2020** [wideblaze/DigSite#36]
for some of the items you can craft it didn't give it to me after I requested it even though I had all the raw materials for it.

**Comment by wideblaze** [comment]
Can you provide specifics? Thanks.

**Comment by minecraftguy2020** [comment]
when I made a robot head it took the materials but did not give the head and same with the mintriation projector I am in version 1.25 when it happened

**Comment by wideblaze** [comment]
In 1.0.26 release notes for the map:
 - fixed sawmill input config at the flame

If your crafting operation attempted to turn logs into planks then it would stall. You can look at the crafting monitors at the edges to see what it’s trying to do / cancel operations and return material. 

I’ll double check current version of the map can fully craft from raw materials. Thanks

**Comment by wideblaze** [comment]
Tested 1.0.27 of map and was not able to replicate. So I think this is resolved. Thanks for reporting.
