### ISSUE TITLE
Modpack Crashes while loading. (Patchouli mod + JAR Launcher)

### ISSUE THREAD

**Issue by ArrZeroZeroTwoSeven** [wideblaze/DigSite#37]
According to the crash screen i guess patchouli is the issue i dont know anything about this kind of stuff but heres the crash log https://paste.dimdev.org/raw/bozuhanefo

i have the launcher set to jar launcher and have java updated all the way

**Comment by wideblaze** [comment]
Attempted reinstall/switch to native launcher/run as admin.  Did not resolve. Native launcher does not work on their computer. They have confirmed java/forge at correct version.

**Comment by wideblaze** [comment]
https://github.com/Vazkii/Patchouli/issues/187

**Comment by wideblaze** [comment]
user installed ONLY Minecraft 1.12 + Patchouli mod and still crashes 

https://pastebin.com/sR508WKu

**Comment by wideblaze** [comment]
Work Around: Had user install pack using MultiMC and the pack was able to load and run
