### ISSUE TITLE
No guardians spawn after destroying guardian spawner

### ISSUE THREAD

**Issue by Xephen** [wideblaze/DigSite#39]
So I've gotten to the part where I need to get a pristine guardian matter for android etc... and I realize that I shouldn't have broken the guardian spawner in the squid because I now can't find them ANYWHERE. It seems the only place they spawn is from that spawner, but it's broken now so I can't find a way to get at least one guardian.

**Comment by wideblaze** [comment]
There are more spawners

1) ship cargo bay

2) bottom of deep abyss (underwater ravine) near ship
