### ISSUE TITLE
unable to load worlds

### ISSUE THREAD

**Issue by chatts121** [wideblaze/DigSite#4]
keeps coming back with problem with ichunutil. tried to use other versions both of this mod and the mod pack but keep getting the same message. evan tried to delete the mod and the mods that depend on it and get a unknown cause for the crash. please help as really like the look of the mod

**Comment by wideblaze** [comment]
please provide crash log

**Comment by chatts121** [comment]
[crash-2019-05-30_14.26.31-client.txt](https://github.com/wideblaze/DigSite/files/3237165/crash-2019-05-30_14.26.31-client.txt)

**Comment by wideblaze** [comment]
looks like it might be related to #1

**Comment by wideblaze** [comment]
possible to allocate more memory?

**Comment by chatts121** [comment]
I try allocate 2gb but get this message from the launcher 
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by chatts121** [comment]
tried turning it down bit by bit from 2gb and got this report after it was down to 1536 mb
[crash-2019-05-30_18.32.00-client.txt](https://github.com/wideblaze/DigSite/files/3238072/crash-2019-05-30_18.32.00-client.txt)

**Comment by wideblaze** [comment]
Unfortunately, you may be just out of luck for now.
It's known to generally work great with 4GB allocated even with memory leak issue. 

I don't want to invest much time in memory issues until #1 is resolved.

**Comment by chatts121** [comment]
I got it to work (well load into a world so far) by using the Minecraft launcher instead of the twitch app thing I think the reason for the problem with the twitch app is that it was using the 32 bit version of java instead of the 64bit and so it was stopping the amount of allocated memory needed.

**Comment by wideblaze** [comment]
That is good news. Thank you so much for sharing the info -- it will be really helpful if others encounter the same problems!

FYI -- you may want to ensure you are running[ latest version](https://minecraft.curseforge.com/projects/digsite/files) on modpack now that you can get it to load. It has a large number of questline improvements and fixes.
