### ISSUE TITLE
Exception Ticking World

### ISSUE THREAD

**Issue by Bluedragon614** [wideblaze/DigSite#41]
Had an issue starting up our digsite server and encountered an "Exception Ticking World". Research online leads us to believe that it has to do with a corrupted Tile Entity, and the crash log suggests it has to do with the Flood Lights mod.

The server won't start up at all, and starting up the world in singleplayer achieves the same error. Seems to have to do with the world file itself.

Here is a link to the full crash log; https://pastebin.com/GPhDaMAX

**Comment by wideblaze** [comment]
There are a couple ways to resolve ticking entity issues. Fastest it to 1) modify the forge config to tell the server to remove erroring entitities. 2) start server, load world, stop the server, 3) modify the forge config back 4) start the server again. The ticking entity will be removed from the world. 
**https://serverminer.com/article/how-to-fix-a-ticking-block-entity-on-a-forge-server/**

**Comment by Bluedragon614** [comment]
Thanks for getting back so fast,

I tried that fix, and still ended up with the same error. It seems Ticking World is different from Ticking Entity, in that Ticking world means the server has no idea where the ticking entity is. 

Crash log looks exactly the same as above

**Comment by wideblaze** [comment]
hmmmm.... OK

backup world (just in case)
remove floodlight mod from client and server
it's not a required mod

le me know if that resolves

**Comment by Bluedragon614** [comment]
I had already tried removing the mod, however, it seems the ticking entity or something of the other is still persisting. It receives a different error "Exception while updating neighbours", which now has to do with a missing block/entity related to Pneumaticraft, MCMultipart and Translocators. It seems this problem runs pretty deep, and this site: https://www.danfry.net/technology/sysadmin/fixing-minecraft-server-issues-exception-while-updating-neighbours/ seems to suggest that I will need some sort of way to remove corrupted sections of our world like MCedit.

Here is the new crash log: https://pastebin.com/qRZT3385

**Comment by wideblaze** [comment]
These things seem unrelated and in different parts of your world (floodlights and translocators)

Maybe the crash caused a world file update issue? I don't know.

In any case this is a bit of a rabbit hole and I don't have simple fixes for you. Maybe best to rollback to a previously good backup if you can. If not:

Your error is here: Block location: World: (98,25,293), Chunk: (at 2,1,5 in 6,18; contains blocks 96,0,288 to 111,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)  https://prnt.sc/r6g79e

you could:

1) use mcedit to correct it. best choice

2) alternatively, you could replace r.0.0.mca world region file with file from /template directory (effectively resetting that section of the map back to default) this may have some unintended consequences but should work

3) or you could remove translocators mod, then in creative break glass at squid to regain access to machines.

**Comment by Bluedragon614** [comment]
I tried all that I could,  but it seems the ticking entity errors just kept on coming. I successfully removed the translocator only to come across more ticking entity errors. I have no idea what we did to our world, but in the end it seemed like the only solution was to move on to a backup. Its a little bit of progress lost, but we'll just have to deal with it.

Thanks for the help anyway!

**Comment by wideblaze** [comment]
OK, glad you were able to revert to backup. Keep me informed if your issue re-appears.
