### ISSUE TITLE
Server crash The Flame (SPOILER ALERT!!)

### ISSUE THREAD

**Issue by archkazs** [wideblaze/DigSite#42]
Hello!

Everytime me (or anyone else from my server) aproaches to The flame, either walking through the desert or via the portal under the Main Chamber

I leave the crash report. I have no clue how to fix it :(

Thanks!
[crash-2020-02-23_10.58.29-server.txt](https://github.com/wideblaze/DigSite/files/4240827/crash-2020-02-23_10.58.29-server.txt)

**Comment by wideblaze** [comment]
I believe this issue is related to a Matter Overdrive Bug with andriod naming. It will add too many characters to an android for some reason.

The world can be fixed using mcedit 

https://github.com/wideblaze/DigSite/issues/20

**Comment by wideblaze** [comment]
https://www.reddit.com/r/feedthebeast/comments/awpww5/ticking_entity_issue/

you may be able to solve the issue by switching to peaceful mode prior to approaching the flame

let me know if any of this fixes work for you

**Comment by archkazs** [comment]
Hey!

So far so good! Changing to peaceful mode to load the chunk seems to work. 

Thank you for respoding so fast!!!

**Comment by wideblaze** [comment]
I was having trouble sleeping so you got lucky ;)

Spoiler alert:
The android-o-matic MAY not function correctly now but it's mostly a sight-gag and not required.
