### ISSUE TITLE
multiplayer questing

### ISSUE THREAD

**Issue by GeneralGerthuim** [wideblaze/DigSite#44]
i am playing Digsite with my friend using Hamachi, and neither of us can talk to the old fisherman to start the questline, but we have advanced far enough to have a house and some simple tools, any way to fix the issue without starting over?

**Comment by wideblaze** [comment]
Exit to main menu (both players) should resolve. Custom NPC can sometimes glitch out. 

Let me know either way, thanks.

**Comment by wideblaze** [comment]
closing this issue, ping me in discord if need additional help on this
