### ISSUE TITLE
Visual glitch with mined blocks

### ISSUE THREAD

**Issue by geezerbahl** [wideblaze/DigSite#47]
Not sure if this is a "feature"/something I need to configure or a bug.  I mined some coal ore (using ~ left-click) and after the blocks were removed it shows up black where they should be.  I added a shader after that to see if that fixed it, but still there.  

Image is without shader:  https://i.ibb.co/jzvVQp0/2020-05-20-14-48-17.png

Image with shader (BSL):  https://i.ibb.co/QCHh4SF/2020-05-20-14-58-47.png

**Comment by wideblaze** [comment]
This is coal gas... somewhat deadly

If you enter coal gas your world may fog
Swim underwater to wash out your eyes

**Comment by geezerbahl** [comment]
Ironic part here.. when I rejoined the little help message on loading screen mentioned this.  How long do I need to swim?  Stayed under until I ran out of breath and it's still there.

**Comment by geezerbahl** [comment]
Actually, it looks like the coal gas effect stays but the fog clears, right?

**Comment by wideblaze** [comment]
Right... the fog effect on the world (for walking into the gas) is removed by swimming... the gas stays... it can dissipate if enough open blocks/light level. Can also place blocks such a dirt to replace/remove gas.
