### ISSUE TITLE
Can't remap Narrator key

### ISSUE THREAD

**Issue by geezerbahl** [wideblaze/DigSite#48]
JourneyMap defaults to using CTRL-B for one of it's screens.  Unfortunately Narrator is bound to this key.  With some modpacks they let you remap (or remove) this binding, but that isn't an option with DigSite.  Would be nice to add the ability to unbind this.

Note - not sure how this is done as I don't see this option in vanilla.

**Comment by wideblaze** [comment]
Exit to title screen, choose options, controls, you can remap any key

**Comment by geezerbahl** [comment]
Remapping of narrator is not part of vanilla - you have to handle this in a mod.  Other modpacks do this, but it isn't an option with yours.  Did you actually try this? I don't see the option from title screen either.  If you do want to fix this I can find other modpacks where this option does show up.  If not, then leave the issue closed.

Up to you - I'm just trying to help.
