### ISSUE TITLE
Pneumaticcraft Drone causes crash when used with Complex Crops

### ISSUE THREAD

**Issue by pyriell** [wideblaze/DigSite#6]
I built one of these hoping to farm cucumbers to trade for polymer clay when farming non-overworld mobs in the Deep Learning setup.  I figured the worst that would happen is that it would just idle, not knowing what to do with plants added by Complex Crops.  After I deployed it, I went to the Ranch to drop some things off, and the internal server suddenly shut down, complaining that these two mods weren't getting along.  It's left my world basically un-loadable.  It shuts down about 5 seconds after it starts up now.

[crash-2019-06-25_20.31.58-server.txt](https://github.com/wideblaze/DigSite/files/3327706/crash-2019-06-25_20.31.58-server.txt)

(Please ignore the world name.  I restarted in a fit of pique after thinking there was a named NPC in the squid, that turned out to be an android named Bishop.  It shot me in the face twice while villagers darted around like frightened cats, and then for some reason hadn't despawned, or maybe just respawned near enough identically, for both of the two attempts I made to retrieve my early-game, but still rather precious, stuff.)

Edit:  I see by your change log that I missed a few updates.  I tested this out quickly with the latest version in a new world, in creative mode, and got the same results as soon as one of the plants became fully grown.

I would imagine this should really be reported to one or both of the other mod authors, but I don't know offhand how to work out which is most responsible, and thought you might want to try something in the meanwhile, like removing the drone, since it's not part of your progression.

**Comment by wideblaze** [comment]
ooof -- that is rough -- probably the fastest / safest fix is to go to backup (the pack does auto backups) 

I'll open an issue with pneumaticraft repressurized but don't expect it to be a priority. Complex crops is not mainstream or getting updates.

I will remove the drone recipe -- thanks! I wasn't happy with it's performance/effort to get working in my test world so I removed the progression line for it / in world drone farm. 

Thanks for reporting this issue!!!

**Comment by wideblaze** [comment]
Work around: do not craft drone. Drone recipe will be removed from pack in next release. Will be readded if issue is resolved.

**Comment by desht** [comment]
This is a bug in Complex Crops, plain and simple.  To be precise, right here: https://github.com/MattCloward/Complex-Crops/blob/master/src/main/java/complexcrops/blocks/BlockCornTop.java#L82

``Block#getDrops`` get a ``IBlockAccess``, not a ``World``, and Complex Crops has no business assuming it's actually a ``World``, and most definitely no business altering the world in a reader method like ``getDrops()``.

**Comment by pyriell** [comment]
I didn't mention it, but it's probably worth noting that I was mainly doing cucumbers, but I also had a row or two of corn around the edges in the survival world.  When I did the creative test, the failure was specifically when corn matured.  I was testing using bonemeal, and it doesn't have any effect on cucumbers as far as I can recall.

Maybe that issue is replicated in the cucumbers, I don't know, but it could have been corn causing it for me every time.  (Actually, looking at the code for cucumbers, I don't see anything like that cast/call.  It probably is just corn.)

**Comment by wideblaze** [comment]
drone recipes were removed in 1.0.02 release
