### ISSUE TITLE
Cardboard box trivialises pneumatic craft security station

### ISSUE THREAD

**Issue by Turmfalke2** [wideblaze/DigSite#7]
hi,

I just played through your pack (at least I killed cybz) and truely enjoyed it.

However in hinsight I feel like the  ~5 mekanism cardboard boxes you get from the storage warehouse are a bit to powerful. They allow picking up spawner, for an easy early mob farm and even more so they allow picking up the pneumatic craft security stations. This allows breaking through sealed of parts of the squid and the sparrow. 
Maybe you should remove/disable them, they aren't crucial to the modpack an they do mean that to this day I still have no clue on how to properly use these worm/nuke chips.

Also the end fight is a bit to easy given that draconic evolution is in the pack.

**Comment by wideblaze** [comment]
Thanks for the heads up on the security station!! I had nerfed it for spawners in the last release but hadn’t seen anyone use it on a station yet.

Glad you enjoyed the pack!

**Comment by wideblaze** [comment]
https://github.com/mekanism/Mekanism/issues/5548

**Comment by wideblaze** [comment]
got a fix from mekanism team -- will be in release 1.0.03 of DigSite

**Comment by wideblaze** [comment]
resolved in 1.0.03 release
