### ISSUE TITLE
XP Rewards crash the server

### ISSUE THREAD

**Issue by Knoxxar** [wideblaze/DigSite#8]
Hi guys,

erytime if anyone get an xp reward from the questbook, the server crashes.

ServerInfos: Debian 9 , 8GB Ram, 2 Cores 3,4 Ghz
Modpack: Version 1.0.02

Croshlog is also here:

https://pastebin.com/SNPTj9WN

**Comment by wideblaze** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/319

**Comment by wideblaze** [comment]
still waiting on a response from mod dev

**Comment by wideblaze** [comment]
work around: do not collect xp rewards from quests -- not essential to gameplay -- xp can be gained by killing mobs

**Comment by wideblaze** [comment]
release 1.0.05 replaces all exp rewards with bottles of enchanting -- this should resolve crashes.

will not be going back to exp rewards even if mod fixes them
